import pandas as pd
configfile: "../config/config.yaml"
SAMPLES = pd.read_csv(config["sample_file"])['Sample']
GROUPS = pd.read_csv(config["sample_file"]).groupby(['condition'])['Sample'].apply(list).to_dict()



include: "rules/common.smk"
include: "rules/trim.smk"
include: "rules/star.smk"
include: "rules/cufflinks.smk"
#include: "rules/htseq.smk"
include: "rules/invert.smk"
#include: "rules/invert_by_group.smk"
#include: "rules/star_untrimmed.smk"


ANNOT = config["annotations"]["combined"]

rule all:
    input:
        expand('../results/invert/{sample}/{sample}_final_results.csv', sample=SAMPLES)
